apiVersion: apps/v1
kind: Deployment
metadata:
  name: footprint-api
  labels:
    app: footprint-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: footprint-api
  template:
    metadata:
      labels:
        app: footprint-api
    spec:
      containers:
      - name: footprint-api
        image: ghcr.io/mathewnwsh/argo-geo-workshop/footprint-api:09b9465d82fa5d4e45d357bab5017b297ae7ca5f
        ports:
        - containerPort: 8000
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: cdse-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: cdse-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_S3_ENDPOINT
          value: "eodata.cloudferro.com"
        - name: AWS_HTTPS
          value: "YES"
        - name: AWS_VIRTUAL_HOSTING
          value: "FALSE"
        - name: GDAL_HTTP_TCP_KEEPALIVE
          value: "YES"
        - name: GDAL_SKIP
          value: "netCDF"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
