[project]
name = "footprint-api"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "rasterio",
    "raster-footprint",
    "antimeridian",
]

[project.scripts]
serve = "uvicorn:main"
